Polish translation
w3c/wai-components pull request #34
Opened 2024-03-07 11:31 UTC by zwiastunsw

I added polish translated for: 
- Essential Components of Web Accessibility (_index.pl.md_)
- Descriptions of Essential Components of Web Accessibility Illustrations (_wai-components-example.pl.md_)

and
- graphics with Polish labels (svg version)

2024-03-15 17:45 UTC, jcabak approved these changes

2024-03-15 17:45 UTC, jcabak commented on content/wai-components-example.pl.md
> +title: Opisy ilustracji w artykule Podstawoe komponenty dostępności Internetu
Podstawowe

2024-03-15 17:45 UTC, jcabak commented on content/wai-components-example.pl.md
> +Ilustracja przedstawia trzy graficznie oznaczone pola obrazujące treść i ludzi. Pośrodku na górze znajduje się pole oznaczone jako „treść” na którym są baletnica, zdjęcie dziecka, znacznik img, tekst
twórców, brak polskiego znaku

2024-03-15 17:45 UTC, jcabak commented on content/wai-components-example.pl.md
> +@@  This is a redundant section. Repeated the relate.png image, but added a different description. (commented by zwiastunsw @@
brak końca nawiasu

2024-03-15 17:45 UTC, jcabak commented on content/wai-components-example.pl.md
> +Ilustracja przedstawia trzy graficznie oznaczone pola obrazujące treść i ludzi. Pośrodku na górze znajduje się pole oznaczone jako „treść” na którym są baletnica, zdjęcie dziecka, znacznik img, tekst
twórców, brak polskiego znaku

2024-03-15 17:46 UTC, jcabak approved these changes

2024-03-26 15:00 UTC, remibetin commented
@zwiastunsw FYI, I have added the remaining instructions in https://github.com/w3c/wai-translations/issues/181

2024-03-26 23:12 UTC, zwiastunsw commented
Related https://github.com/w3c/wai-website-data/pull/140

2024-03-27 23:17 UTC, zwiastunsw commented
@remibetin 
The link to the illustration descriptions does not work for an incomprehensible reason.
An error is reported on line 4 during the build: 
``` 
YAML Exception reading /opt/build/repo/content/wai-components-example.pl.md: (<unknown>): 
did not find expected key while parsing a block mapping at line 4 column 1
```

2024-04-04 14:13 UTC, remibetin commented
@zwiastunsw I have opened a PR to fix the problem, can you merge it? https://github.com/lepszyweb/wai-components/pull/1

Can you check "Allow edits by maintainers" so I can directly fix issues like this in your PRs?

2024-04-08 14:35 UTC, remibetin commented on content/index.pl.md
> +-   **wytyczne WAI** - WCAG, ATAG i UAAG, wymienione w dalszej części - określają, jak wdrożyć tekst alternatywny w&nbsp;różnych komponentach, aby zwiększyć dostępność
```suggestion
-   **wytyczne WAI** - WCAG, ATAG i UAAG, wymienione w dalszej części - określają, jak wdrożyć tekst alternatywny w&nbsp;różnych komponentach, aby zwiększyć dostępność
```

A link is missing here. Original version is `([WCAG, ATAG, UAAG described below](#guidelines))`

2024-04-08 14:38 UTC, remibetin commented on content/index.pl.md
> +-   użytkownicy mogą wykonać więcej pracy, aby zrekompensować  brak obsługi dostępności w przeglądarkach, odtwarzaczach mediów lub technologiach wspomagających; na przykład, używając innej przeglądar
@zwiastunsw A paragraph from the original version is missing in the translation:

> However, in most cases the works-arounds are not implemented and the result is still poor accessibility. Additionally, sometimes poor accessibility support in one component cannot be reasonably overcome by other components and the result is inaccessibility, making it impossible for some people with disabilities to use a particular website, page, or feature.

2024-04-08 14:39 UTC, remibetin commented on content/index.pl.md
> +Inicjatywa na Rzecz Dostępności Internetu [WAI](https://www.w3.org/WAI/)) w Konsorcjum <span lang="en">World Wide Web</span> ([W3C](https://www.w3.org/)) opracowuje **standardy dostępności cyfrowej**
```suggestion
Inicjatywa na Rzecz Dostępności Internetu ([WAI](https://www.w3.org/WAI/)) w Konsorcjum <span lang="en">World Wide Web</span> ([W3C](https://www.w3.org/)) opracowuje **standardy dostępności cyfrowej** dla różnych komponentów:
```

A parenthesis is missing

2024-04-08 14:42 UTC, remibetin commented on content/index.pl.md
> +-   [[Wytyczne dla dostępności narzędzi autorskich (ATAG)]](/standards-guidelines/atag) dotyczące narzędzi do tworzenia treści
```suggestion
-   [[Wytyczne dla dostępności narzędzi autorskich (ATAG)]](/standards-guidelines/atag/) dotyczące narzędzi do tworzenia treści
```

To fix a problem with the rendered link.

2024-04-08 14:45 UTC, remibetin requested changes
Thank you @zwiastunsw for this new translation!

I have added some comments for your consideration. 

Can you also please remove the `content.png`, `relate-developer.png`, `relate-example` & `relate-users.png` from this PR, since they are not used in the resource?

Let me know when you have done the changes so I can check the PR again.

Thanks!

2024-04-08 20:51 UTC, zwiastunsw commented
@remibetin thanks, fixed

2024-04-08 22:07 UTC, remibetin approved these changes

2024-04-09 12:59 UTC, merged

2024-04-09 13:19 UTC, remibetin commented
This translation has been published today 🚀 Thank you @zwiastunsw!

See https://www.w3.org/WAI/fundamentals/components/pl & https://www.w3.org/WAI/fundamentals/components/examples/pl

2024-04-09 13:20 UTC, remibetin commented
QA done: ✅